### ISSUE TITLE
API

### ISSUE THREAD

**Issue by vuthehuyht** [vuthehuyht/se04-nhom5.1#13]
API cung cấp dữ liệu cho bên ngoài sử dụng tuỳ mục đích

**Comment by ToNguyen2612** [comment]
Cung cấp những dữ liệu gì?? Đã thiết kế endpoint API chưa

**Comment by vuthehuyht** [comment]
Endpoint API chứa thông tin về post, product, page

**Comment by sonnguyezz** [comment]
Trong wordpress đã hỗ trợ api rồi, chỉ việc custom lại dùng thôi
