### ISSUE TITLE
Clone Product Data

### ISSUE THREAD

**Issue by vuthehuyht** [vuthehuyht/se04-nhom5.1#7]

**Comment by ToNguyen2612** [comment]
Ý tưởng của phần này là gì???

**Comment by sonnguyezz** [comment]
Clone trang product về và chỉnh sửa lại giao diện thôi

**Comment by vuthehuyht** [comment]
Như thế có nhọc quá không thế

**Comment by sonnguyezz** [comment]
Sửa lại một chút cho nó khác đi, chứ để giống y sì thế không hay. Chốt như thế nhé
